[25/Jul/2016 13:45:42] INFO [blog.views:10] Handling post_list GET request
[25/Jul/2016 13:45:44] WARNING [django.request:182] Not Found: /favicon.ico
[25/Jul/2016 13:46:25] INFO [accounts.views:12] Handling register GET request
[25/Jul/2016 13:49:16] INFO [blog.views:10] Handling post_list GET request
[25/Jul/2016 13:49:23] INFO [accounts.views:12] Handling register GET request
[25/Jul/2016 13:49:25] INFO [accounts.views:42] Handling login GET request
[25/Jul/2016 13:49:27] INFO [blog.views:10] Handling post_list GET request
[25/Jul/2016 13:49:28] INFO [blog.views:24] Handling new_post GET request
[25/Jul/2016 13:50:45] INFO [blog.views:10] Handling post_list GET request
[25/Jul/2016 14:12:17] INFO [blog.views:10] Handling post_list GET request
[25/Jul/2016 14:12:23] INFO [blog.views:16] Handling post_details GET request
[25/Jul/2016 14:12:25] WARNING [django.request:182] Not Found: /blog/5/edit
[25/Jul/2016 14:12:56] WARNING [django.request:182] Not Found: /blog/5/edit
[25/Jul/2016 14:13:01] INFO [blog.views:39] Handling edit_post GET request
[25/Jul/2016 14:13:35] INFO [blog.views:39] Handling edit_post POST request
[25/Jul/2016 14:13:35] ERROR [django.request:284] Internal Server Error: /blog/5/edit
Traceback (most recent call last):
  File "C:\Users\Ciaran\Niall\CodeInst\stream3\virtual_env\hack_blog\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Ciaran\Niall\CodeInst\stream3\virtual_env\hack_blog\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Ciaran\Niall\CodeInst\stream3\hack_blog\blog\views.py", line 45, in edit_post
    post.author = request.user
  File "C:\Users\Ciaran\Niall\CodeInst\stream3\virtual_env\hack_blog\lib\site-packages\django\db\models\fields\related_descriptors.py", line 207, in __set__
    self.field.remote_field.model._meta.object_name,
ValueError: Cannot assign "<SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x031ECBF0>>": "Post.author" must be a "User" instance.
[25/Jul/2016 14:13:58] INFO [blog.views:39] Handling edit_post POST request
[25/Jul/2016 14:13:58] ERROR [django.request:284] Internal Server Error: /blog/5/edit
Traceback (most recent call last):
  File "C:\Users\Ciaran\Niall\CodeInst\stream3\virtual_env\hack_blog\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Ciaran\Niall\CodeInst\stream3\virtual_env\hack_blog\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Ciaran\Niall\CodeInst\stream3\hack_blog\blog\views.py", line 45, in edit_post
    post.author = request.user
  File "C:\Users\Ciaran\Niall\CodeInst\stream3\virtual_env\hack_blog\lib\site-packages\django\db\models\fields\related_descriptors.py", line 207, in __set__
    self.field.remote_field.model._meta.object_name,
ValueError: Cannot assign "<SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x032779B0>>": "Post.author" must be a "User" instance.
[25/Jul/2016 14:14:16] INFO [accounts.views:42] Handling login GET request
[25/Jul/2016 14:14:28] INFO [accounts.views:42] Handling login POST request
[25/Jul/2016 14:14:32] INFO [accounts.views:42] Handling login POST request
[25/Jul/2016 14:14:35] INFO [accounts.views:42] Handling login POST request
[25/Jul/2016 14:14:45] INFO [accounts.views:42] Handling login POST request
[25/Jul/2016 14:14:47] INFO [accounts.views:12] Handling register GET request
[25/Jul/2016 14:15:03] INFO [accounts.views:12] Handling register POST request
[25/Jul/2016 14:15:03] INFO [accounts.views:42] Handling login GET request
[25/Jul/2016 14:15:15] INFO [accounts.views:42] Handling login POST request
[25/Jul/2016 14:15:35] INFO [blog.views:10] Handling post_list GET request
[25/Jul/2016 14:15:37] INFO [blog.views:16] Handling post_details GET request
[25/Jul/2016 14:15:38] INFO [blog.views:39] Handling edit_post GET request
[25/Jul/2016 14:15:56] INFO [blog.views:39] Handling edit_post POST request
[25/Jul/2016 14:15:57] INFO [blog.views:16] Handling post_details GET request
[25/Jul/2016 14:16:03] INFO [blog.views:10] Handling post_list GET request
[25/Jul/2016 14:16:16] INFO [blog.views:16] Handling post_details GET request
[25/Jul/2016 14:16:16] WARNING [django.request:182] Not Found: /media/images/avatar_46BGy04.jpg
[25/Jul/2016 14:16:17] INFO [blog.views:39] Handling edit_post GET request
[25/Jul/2016 14:16:48] INFO [blog.views:39] Handling edit_post POST request
[25/Jul/2016 14:16:48] INFO [blog.views:16] Handling post_details GET request
[25/Jul/2016 14:16:49] WARNING [django.request:182] Not Found: /media/images/avatar_46BGy04.jpg
[25/Jul/2016 14:16:59] INFO [blog.views:10] Handling post_list GET request
[25/Jul/2016 14:17:05] INFO [accounts.views:63] Handling logout GET request
[25/Jul/2016 14:17:05] INFO [blog.views:10] Handling post_list GET request
[25/Jul/2016 14:17:07] INFO [accounts.views:12] Handling register GET request
[25/Jul/2016 14:17:25] INFO [accounts.views:12] Handling register POST request
[25/Jul/2016 14:17:25] INFO [accounts.views:42] Handling login GET request
[25/Jul/2016 14:17:35] INFO [accounts.views:42] Handling login POST request
[25/Jul/2016 14:17:38] INFO [blog.views:10] Handling post_list GET request
[25/Jul/2016 14:17:40] INFO [blog.views:16] Handling post_details GET request
[25/Jul/2016 14:17:40] WARNING [django.request:182] Not Found: /media/images/avatar_46BGy04.jpg
[25/Jul/2016 14:17:41] INFO [blog.views:39] Handling edit_post GET request
[25/Jul/2016 14:17:56] INFO [blog.views:39] Handling edit_post POST request
[25/Jul/2016 14:17:56] INFO [blog.views:16] Handling post_details GET request
[25/Jul/2016 14:17:56] WARNING [django.request:182] Not Found: /media/images/avatar_46BGy04.jpg
